### PR TITLE
fix: add workaround on wallet connectors to remove from localStorage

### LINKED ISSUE #256: BUG: In some cases, `useAutoConnect` will keep reconnecting even if user has clicked disconnect
## Issue Overview

In some cases, `useAutoConnect` will keep reconnecting even if user has clicked disconnect. Produced in https://github.com/Quantum3-Labs/speedrunstark/issues/110.

## Proposed Solutions or Ideas

- Delete localStorage data upon disconnecting
- (Nice-to-have) abstract away `disconnect()` function cleanly to delete the data without additional calls

### PR DESCRIPTION
**Pull request by metalboyrick**
# Task name here

Fixes #256 
Fixes https://github.com/Quantum3-Labs/speedrunstark/issues/110

## Types of change

- [ ] Feature
- [X] Bug
- [ ] Enhancement

## Comments (optional)

- Note this is  a workaround that tampers with the `disconnect()` function of the connector. I've injected a local storage removal operation to clear local storage so that `useAutoConnect()` does not go in a infinite loop when it finds something stored.
- Should be able to resolve the issue in speedrunstark (https://github.com/Quantum3-Labs/speedrunstark/issues/110) as well @gianalarcon

### CODE REVIEW

File: packages/nextjs/services/web3/connectors.tsx [hunk 1]
```diff
@@ -18,7 +29,7 @@ function getConnectors() {
     connectors.push(new BurnerConnector());
   }
 
-  return connectors.sort(() => Math.random() - 0.5);
+  return connectors.sort(() => Math.random() - 0.5).map(withDisconnectWrapper);
```
Comment (gianalarcon) [inline packages/nextjs/services/web3/connectors.tsx:32]: It will be also a great chance to refactor this sort using Math.random() - 0.5, what do you think? @jrcarlos2000

Comment (metalboyrick) [reply packages/nextjs/services/web3/connectors.tsx:32]: are we considering to use `lodash` ?

Comment (0xquantum3labs) [reply packages/nextjs/services/web3/connectors.tsx:32]: @metalboyrick i think something like [this](https://github.com/Quantum3-Labs/scaffold-stark-2/pull/152/files) ?

Comment (0xquantum3labs) [reply packages/nextjs/services/web3/connectors.tsx:32]: this connectors file was updated when we tried to have a conditional connector list, that doesnt show the burner connector when the target network is not `devnet`.

**Review by 0xquantum3labs — APPROVED** [review]

File: packages/nextjs/services/web3/connectors.tsx (hunk 1 above)
Comment (0xquantum3labs) [reply packages/nextjs/services/web3/connectors.tsx:32]: if its possible to go back to use [this](https://github.com/apibara/starknet-react/blob/852f202a48e6a347ffa950fd4fb2c794702699b6/packages/core/src/connectors/discovery.ts#L21) hook from `starknet-react` , wdyt ? @metalboyrick

Comment (metalboyrick) [reply packages/nextjs/services/web3/connectors.tsx:32]: better make new pr i think, refactoring change

Comment (metalboyrick) [reply packages/nextjs/services/web3/connectors.tsx:32]: options: either to use lodash shuffle or implement our own array shuffles, or use this hook, i think both works. Either way we still need the disconnect wrapper to ensure that wallet disconnects AND removes the local storage entry

Comment (metalboyrick) [reply packages/nextjs/services/web3/connectors.tsx:32]: just checked the `useInjectedConnector` from starknet react, they use `lodash` shuffle under the hood haha.
