### PR TITLE
fix: do not show wallet not deployed in wrong network

### LINKED ISSUE #260: [BUG] Wallet Not Deployed incorrect rendering
## Issue Overview

Wallet not deployed message rendered on incorrect occasions:
1.  Connected to wrong network
2. Fresh account deployed but still showing the error

Also happening: https://github.com/Quantum3-Labs/speedrunstark/issues/111

- Create a new wallet
- Try to connect , should display "wallet not deployed", this is expected since we have not deployed the wallet yet
- Fund the wallet and deploy (DO NOT REFRESH)
- Disconnect from the wallet 
- Reconnect the wallet
- Wallet not deployed should still be shown.

NOTE: Refreshing removes this bug.

## Proposed Solutions or Ideas

- Check for "wallet not deployed" rendering logic
- Check rerendering logic, might be some cache issues

### PR DESCRIPTION
**Pull request by metalboyrick**
# Task name here

Fixes #260 
FIxes https://github.com/Quantum3-Labs/speedrunstark/issues/111

## Types of change

- [ ] Feature
- [X] Bug
- [ ] Enhancement

### CODE REVIEW

File: packages/nextjs/components/Header.tsx [hunk 1]
```diff
@@ -78,18 +78,23 @@ export const Header = () => {
...
   useEffect(() => {
-    if (status === "connected" && address) {
-      provider.getContractVersion(address).catch((e) => {
-        if (e.toString().includes("Contract not found")) {
-          setIsDeployed(false);
-        }
-      });
+    if (status === "connected" && address && chainId === targetNetwork.id) {
+      provider
+        .getContractVersion(address)
```
Comment (0xquantum3labs) [inline packages/nextjs/components/Header.tsx:87]: lets change this to use `getClassHashAt` , i experienced some weird behavior using this helper function. When moving from non deployed account to another non deployed account, also this will be similar to the way we do it [here](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/33111d7ab6deb94e359c30d3aa917402e0dba865/packages/nextjs/hooks/scaffold-stark/useDeployedContractInfo.ts#L41) in `useScaffoldContractInfo()`

**Review by 0xquantum3labs — CHANGES_REQUESTED** [review]

File: packages/nextjs/components/Header.tsx (hunk 1 above)
Comment (0xquantum3labs) [reply packages/nextjs/components/Header.tsx:87]: cc : @Nadai2010

**Review by 0xquantum3labs — APPROVED** [review]
